resource_types:
- name: git-branches
  type: docker-image
  source:
    repository: vito/git-branches-resource

resources:
  - name: demo
    type: git-branches
    source:
      uri: https://github.com/gumshuda404/multiBranchConcourse.git
jobs:
  - name: create-pipelines
    public: false
    plan:
      - get: demo
        trigger: true
      - task: create-pipelines
        file: demo/create-pipeline.yml
