#resource_types:
#- name: git-branches
# type: docker-image
# source:
#     repository: vito/git-branches-resource

resource_types:
- name: git-branches
  type: registry-image
  source:
    repository: openstax/concourse-resource-github-issue

resources:
  - name: demo
    type: git-branches
    source:
      uri: https://github.com/gumshuda404/multiBranchConcourse.git
jobs:
  - name: create-pipelines
    public: false
    plan:
      - get: demo
        trigger: true
      - task: create-pipelines
        config:
          inputs:
             - name: branches
          outputs:
             - name: output
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: teliaoss/concourse-awscli
              tag: latest
          run:
            path: demo/create-pipeline.sh
